spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update #validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG